#!/usr/bin/env python3
#Copyright 2009 Sebastian Hagen
# This file is part of luteus.
#
# luteus is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# luteus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with luteus.  If not, see <http://www.gnu.org/licenses/>.

def main():
   import sys
   import os.path
   
   path = os.path.realpath(os.path.abspath(sys.argv[0]))
   updir = os.path.split(os.path.split(path)[0])[0]
   ldir = os.path.join(updir, 'luteus')
   if (os.path.exists(ldir)):
      print('Using luteus lib from {0!a}.'.format(ldir))
      sys.path.insert(0, updir)
      import luteus.core.main
      del(sys.path[0])
   else:
      import luteus.core.main
   
   luteus.core.main.main()
   

if (__name__ == '__main__'):
   main()
